version: "3.8"
services:
  app:
    image: micro-pump-tg:latest # Ensure this matches the tag used during the build
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: